//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.RepartidorServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RepartidorServiceReference.IRepartidor")]
    public interface IRepartidor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/GetAll", ReplyAction="http://tempuri.org/IRepartidor/GetAllResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Repartidor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.UnidadEntrega))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.EstatusUnidad))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/GetAll", ReplyAction="http://tempuri.org/IRepartidor/GetAllResponse")]
        System.Threading.Tasks.Task<object[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/GetById", ReplyAction="http://tempuri.org/IRepartidor/GetByIdResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.UnidadEntrega))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.EstatusUnidad))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        ML.Repartidor GetById(int idRepartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/GetById", ReplyAction="http://tempuri.org/IRepartidor/GetByIdResponse")]
        System.Threading.Tasks.Task<ML.Repartidor> GetByIdAsync(int idRepartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/Add", ReplyAction="http://tempuri.org/IRepartidor/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.UnidadEntrega))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.EstatusUnidad))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        bool Add(ML.Repartidor repartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/Add", ReplyAction="http://tempuri.org/IRepartidor/AddResponse")]
        System.Threading.Tasks.Task<bool> AddAsync(ML.Repartidor repartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/Update", ReplyAction="http://tempuri.org/IRepartidor/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.UnidadEntrega))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.EstatusUnidad))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        bool Update(ML.Repartidor repartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/Update", ReplyAction="http://tempuri.org/IRepartidor/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(ML.Repartidor repartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/Delete", ReplyAction="http://tempuri.org/IRepartidor/DeleteResponse")]
        bool Delete(int idRepartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidor/Delete", ReplyAction="http://tempuri.org/IRepartidor/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int idRepartidor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRepartidorChannel : PL.RepartidorServiceReference.IRepartidor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RepartidorClient : System.ServiceModel.ClientBase<PL.RepartidorServiceReference.IRepartidor>, PL.RepartidorServiceReference.IRepartidor {
        
        public RepartidorClient() {
        }
        
        public RepartidorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RepartidorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepartidorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepartidorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<object[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public ML.Repartidor GetById(int idRepartidor) {
            return base.Channel.GetById(idRepartidor);
        }
        
        public System.Threading.Tasks.Task<ML.Repartidor> GetByIdAsync(int idRepartidor) {
            return base.Channel.GetByIdAsync(idRepartidor);
        }
        
        public bool Add(ML.Repartidor repartidor) {
            return base.Channel.Add(repartidor);
        }
        
        public System.Threading.Tasks.Task<bool> AddAsync(ML.Repartidor repartidor) {
            return base.Channel.AddAsync(repartidor);
        }
        
        public bool Update(ML.Repartidor repartidor) {
            return base.Channel.Update(repartidor);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(ML.Repartidor repartidor) {
            return base.Channel.UpdateAsync(repartidor);
        }
        
        public bool Delete(int idRepartidor) {
            return base.Channel.Delete(idRepartidor);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int idRepartidor) {
            return base.Channel.DeleteAsync(idRepartidor);
        }
    }
}
